name: Execute django environment

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout the projects code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Upgrade python system packages
        run: pip install -U pip wheel setuptools

      - uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{env.DB_USER}}
          password: ${{env.DB_PASSWORD}}
          database: ${{env.DB_NAME}}
          port: ${{env.DB_PORT}}
        id: postgres

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --system --deploy --ignore-pipfile

      - name: Create temp log file for pytest
        run: |
          sudo mkdir /var/log/app
          sudo touch /var/log/app/webapp.log
          sudo chown -R $USER:$USER /var/log/app

      - name: Run migrations
        run: |
          python manage.py migrate


      # - name: exit
      #   run: exit 1
