name: Packer Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DEBUG: "True"

    steps:
      - name: Checkout the projects code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Upgrade python system packages
        run: pip install -U pip wheel setuptools

      - uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{env.DB_USER}}
          password: ${{env.DB_PASSWORD}}
          database: ${{env.DB_NAME}}
          port: ${{env.DB_PORT}}
        id: postgres

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --system --deploy --ignore-pipfile

      - name: zip unzip
        run: |
          zip -r csye6225.zip .

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          pytest

      - name: Set up GCP credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Install packer gcp plugin
        run: packer plugins install github.com/hashicorp/googlecompute

      - name: Packer build
        run: packer build -force -only=googlecompute.centos-csye-deploy ./packer_setup
