name: Packer Deploy

on:
  workflow_run:
    workflows: ["Execute django environment"]
    types:
      - completed

jobs:
  packer_build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ env.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Install Packer
        uses: hashicorp/setup-packer@v1.0.3
        id: setup

      - name: Install packer gcp plugin
        run: packer plugins install github.com/hashicorp/googlecompute

      - name: Packer build
        run: packer build -force -only=googlecompute ./`packer_setup
